export enum AppSettingId {
	SALESFORCE_BOT_USERNAME = 'salesforce_bot_username',
	SALESFORCE_BOT_PASSWORD = 'salesforce_bot_password',
	SF_HANDOVER_DEPARTMENT_NAME = 'handover_department_name',
	CHAT_BOT_USERNAME = 'chat_bot_username',
	CHAT_BOT_PASSWORD = 'chat_bot_password',
	CB_HANDOVER_DEPARTMENT_NAME = 'chat_handover_department_name',
	SALESFORCE_CHAT_API_ENDPOINT = 'salesforce_chat_api_endpoint',
	SALESFORCE_ORGANISATION_ID = 'salesforce_organisation_id',
	SALESFORCE_DEPLOYMENT_ID = 'salesforce_deployment_id',
	SALESFORCE_BUTTON_ID = 'salesforce_button_id',
	LIVEAGENT_CHAT_ENDED_MESSAGE = 'la_chat_ended_message',
	LIVEAGENT_QUEUE_POSITION_MESSAGE = 'la_queue_position_message',
	LIVEAGENT_QUEUE_EMPTY_MESSAGE = 'la_queue_empty_message',
	LIVEAGENT_NO_QUEUE_MESSAGE = 'la_no_queue_message',
	NO_LIVEAGENT_AGENT_AVAILABLE_MESSAGE = 'la_no_liveagent_available',
	TECHNICAL_DIFFICULTY_MESSAGE = 'technical_difficulty_message',
	DEBUG_BUTTON = 'debug_button',
}
