export enum AppSettingId {
	SALESFORCE_BOT_USERNAME = 'salesforce_bot_username',
	SF_HANDOVER_DEPARTMENT_NAME = 'handover_department_name',
	CB_HANDOVER_DEPARTMENT_NAME = 'chat_handover_department_name',
	CHATBOT_USERNAME = 'chat_bot_username',
	DIALOGFLOW_ENABLE_END_EVENT = 'dialogflow_enable_end_event',
	DIALOGFLOW_AGENT_ENDED_CHAT_EVENT_NAME = 'dialogflow_agent_ended_chat_event_name',
	DIALOGFLOW_AGENT_UNAVAILABLE_EVENT_NAME = 'dialogflow_agent_unavailable_event_name',
	DIALOGFLOW_SESSION_ERROR_EVENT_NAME = 'dialogflow_session_error_event_name',
	DIALOGFLOW_CUSTOMER_IDLE_TIMEOUT_EVENT_NAME = 'dialogflow_customer_idle_timeout_event_name',
	DIALOGFLOW_END_EVENT_LANGUAGE_CODE = 'dialogflow_end_event_language_code',
	SALESFORCE_CHAT_API_ENDPOINT = 'salesforce_chat_api_endpoint',
	SALESFORCE_ORGANISATION_ID = 'salesforce_organisation_id',
	SALESFORCE_DEPLOYMENT_ID = 'salesforce_deployment_id',
	SALESFORCE_BUTTON_ID = 'salesforce_button_id',
	FINDING_LIVEAGENT_MESSAGE = 'finding_liveagent_message',
	LIVEAGENT_CHAT_ENDED_MESSAGE = 'la_chat_ended_message',
	LIVEAGENT_QUEUE_POSITION_MESSAGE = 'la_queue_position_message',
	LIVEAGENT_NO_QUEUE_MESSAGE = 'la_no_queue_message',
	NO_LIVEAGENT_AGENT_AVAILABLE_MESSAGE = 'la_no_liveagent_available',
	TECHNICAL_DIFFICULTY_MESSAGE = 'technical_difficulty_message',
	CUSTOMER_TIMEOUT_WARNING_MESSAGE = 'customer_timeout_warning_message',
	DEBUG_BUTTON = 'debug_button',
}
