export enum ErrorLogs {
	HANDOVER_ENDPOINT_REQUEST_FAILED = 'Error completing recieved handover endpoint request.',
	AVAILABILITY_ENDPOINT_REQUEST_ERROR = 'Error completing recieved availability endpoint request.',
	CHECKING_AVAILABILITY_ERROR = 'Error checking availabilty from Salesforce Org.',
	SALESFORCE_CHAT_API_NOT_FOUND = 'Salesforce Chat API endpoint not found.',
	ROCKETCHAT_SERVERURL_NOT_FOUND = 'Rocket Chat Server URL not found.',
	GETTING_LIVEAGENT_RESPONSE_ERROR = 'Error getting Liveagent response.',
	SENDING_LIVEAGENT_CHAT_REQUEST_ERROR = 'Error sending Liveagent chat request.',
	GENERATING_LIVEAGENT_SESSION_ID_ERROR = 'Error generating Liveagent session ID.',
	CLOSING_LIVEAGENT_SESSION_ERROR = 'Error closing Liveagent Session.',
	SENDING_MESSAGE_TO_LIVEAGENT_ERROR = 'Error sending message to Liveagent.',
	LIVEAGENT_SESSION_CLASS_FAILED = 'Unexpected error occured in LiveAgentSession class.',
	UNCALCULATED_AGENT_EVENT_TYPE = 'Uncalculated agent event type recieved.',
	ALL_LIVEAGENTS_UNAVAILABLE = 'No Liveagent available right now.',
	APP_CONFIGURATION_INVALID = 'Entered app configurations are invalid. Please recheck.',
	SALESFORCE_INTERNAL_FAILURE = 'Internal failure in Saleforce Org. Please check your org for potential issues.',
	UNKNOWN_ERROR_IN_CHECKING_AGENT_RESPONSE = 'Unknown error occured while checking for Liveagent chat request.',
	LIVEAGENT_SESSION_EXPIRED = 'Liveagent session expired.',
	INVALID_ROOM_ID = 'Room Id not valid.',
	INVALID_VISITOR_TOKEN = 'Visitor token not found.',
	INVALID_DEPARTMENT_NAME = 'Invalid target department name.',
	HANDOVER_REQUEST_FAILED = 'Handover request failed.',
	SERVEDBY_NOT_FOUND = 'Livechat Rooms servedBy property missing',
	ENDCHAT_EVENT_PARAMS_ISSUE = 'Dialogflow end chat event params missing/invalid.',
	ENDCHAT_EVENT_API_CALL_FAIL = 'Cannot successfully call Dialogflow app incoming endpoint.',
	DIALOGFLOW_ERROR_SESSION = 'Error encountered in session. Triggering DIALOGFLOW_SESSION_ERROR_EVENT',
	CHASITOR_TYPING_API_CALL_FAIL = 'Cannot successfully call ChasitorTyping/ChasitorNotTyping api.',
}
